apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-nodeapp
    app.kubernetes.io/part-of: test-application
  name: test-nodeapp
  namespace: jephilli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-nodeapp
    spec:
      containers:
      - image: quay.io/karthik_jk/test-nodeapp@sha256:5364035ae502d6bdc54c7c4df4f64163f017b5e12fafef817e96b2b981f85980
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
